### ISSUE TITLE
Invalid app

### ISSUE THREAD

**Issue by armandfrigo** [eapowertools/qs-app-metadata-analyzer#1]
Hi Daniel,
Cannot import the app in June 2018 SP1, I get an error "Invalid app".
Any idea?
The logs I found only show the same vague error message.
Armand

**Comment by danielpilla** [comment]
Hi Armand,
I just tested on June 2018 as well as Sept 2018 and could not replicate your issue. That said, the app was saved initially in Sept of 2018. I've imported the app into a June 2018 environment, saved, and committed. Please try with the latest release and let me know if that resolves your issue.

https://github.com/eapowertools/qs-app-metadata-analyzer/releases

Cheers,

**Comment by danielpilla** [comment]
Hi Armand,
I just tested importing the app into June 2018 SP1 with success, and cannot replicate your issue. Please attempt to download the latest release and try again. I am closing the issue as I cannot replicate it.

Cheers,

**Comment by armandfrigo** [comment]
Hi Daniel, the latest built worked for me as well on D/Q/P systems. 
Thanks.
Armand
